-- Generated by import.py

INSERT INTO regular_expressions (name, pattern) VALUES ('German DL :: German DL', '(?i)german\s*\.?dl|(?<=\bGerman\b.*)(?<!\bWEB[-_. ])\bDL\b|\[DE\+[a-z]{2}\]|\[[a-z]{2}\+DE\]|ger,\s*[a-z]{3}\]|\[[a-z]{3}\s*,\s*ger\]');
INSERT INTO regular_expressions (name, pattern) VALUES ('German DL 2 :: NOT German DL', '(?i)german\s*\.?dl|(?<=\bGerman\b.*)(?<!\bWEB[-_. ])\bDL\b|\[DE\+[a-z]{2}\]|\[[a-z]{2}\+DE\]|ger,\s*[a-z]{3}\]|\[[a-z]{3}\s*,\s*ger\]');
INSERT INTO regular_expressions (name, pattern) VALUES ('Language: German Only :: NOT German DL', '(?i)german\s*\.?dl|(?<=\bGerman\b.*)(?<!\bWEB[-_. ])\bDL\b|\[DE\+[a-z]{2}\]|\[[a-z]{2}\+DE\]|ger,\s*[a-z]{3}\]|\[[a-z]{3}\s*,\s*ger\]');
INSERT INTO regular_expressions (name, pattern) VALUES ('Language: Not ENG/GER :: Not German in Title', '(?i)\bgerman\b');