-- Generated by import.py

INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('German DL', '', 1);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('German DL 2', '', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Language: German Only', '', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Language: Not ENG/GER', '', 0);