-- Generated by import.py

-- Custom Format Conditions

INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('German DL', 'German DL', 'release_title', 'all', 0, 1);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('German DL 2', 'NOT German DL', 'release_title', 'all', 1, 1);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('German DL 2', 'German', 'language', 'all', 0, 1);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('German DL 2', 'English', 'language', 'all', 0, 1);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Language: German Only', 'Language GER', 'language', 'all', 0, 1);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Language: German Only', 'NOT German DL', 'release_title', 'all', 1, 1);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Language: German Only', 'Not English', 'language', 'all', 1, 1);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Language: Not ENG/GER', 'Not English Language', 'language', 'all', 1, 1);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Language: Not ENG/GER', 'Not German Language', 'language', 'all', 1, 1);
INSERT INTO custom_format_conditions (custom_format_name, name, type, arr_type, negate, required) VALUES ('Language: Not ENG/GER', 'Not German in Title', 'release_title', 'all', 1, 1);

-- Condition Patterns

INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('German DL', 'German DL', 'German DL :: German DL');
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('German DL 2', 'NOT German DL', 'German DL 2 :: NOT German DL');
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Language: German Only', 'NOT German DL', 'Language: German Only :: NOT German DL');
INSERT INTO condition_patterns (custom_format_name, condition_name, regular_expression_name) VALUES ('Language: Not ENG/GER', 'Not German in Title', 'Language: Not ENG/GER :: Not German in Title');

-- Condition Languages

INSERT INTO condition_languages (custom_format_name, condition_name, language_name, except_language) VALUES ('German DL 2', 'German', 'German', 0);
INSERT INTO condition_languages (custom_format_name, condition_name, language_name, except_language) VALUES ('German DL 2', 'English', 'English', 0);
INSERT INTO condition_languages (custom_format_name, condition_name, language_name, except_language) VALUES ('Language: German Only', 'Language GER', 'German', 0);
INSERT INTO condition_languages (custom_format_name, condition_name, language_name, except_language) VALUES ('Language: German Only', 'Not English', 'English', 0);
INSERT INTO condition_languages (custom_format_name, condition_name, language_name, except_language) VALUES ('Language: Not ENG/GER', 'Not English Language', 'English', 0);
INSERT INTO condition_languages (custom_format_name, condition_name, language_name, except_language) VALUES ('Language: Not ENG/GER', 'Not German Language', 'German', 0);
