-- Generated by import.py

INSERT OR IGNORE INTO tags (name) VALUES ('1080p');
INSERT OR IGNORE INTO tags (name) VALUES ('480p');
INSERT OR IGNORE INTO tags (name) VALUES ('4K');
INSERT OR IGNORE INTO tags (name) VALUES ('720p');
INSERT OR IGNORE INTO tags (name) VALUES ('German');