-- Generated by import.py

INSERT INTO quality_profile_tags (quality_profile_name, tag_name) VALUES ('German 1080p', 'German');
INSERT INTO quality_profile_tags (quality_profile_name, tag_name) VALUES ('German 1080p', '1080p');
INSERT INTO quality_profile_tags (quality_profile_name, tag_name) VALUES ('German 480p', 'German');
INSERT INTO quality_profile_tags (quality_profile_name, tag_name) VALUES ('German 480p', '480p');
INSERT INTO quality_profile_tags (quality_profile_name, tag_name) VALUES ('German 4K', 'German');
INSERT INTO quality_profile_tags (quality_profile_name, tag_name) VALUES ('German 4K', '4K');
INSERT INTO quality_profile_tags (quality_profile_name, tag_name) VALUES ('German 720p', 'German');
INSERT INTO quality_profile_tags (quality_profile_name, tag_name) VALUES ('German 720p', '720p');